trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: 'your-azure-devops-variable-group'  # Replace with your Azure DevOps variable group

stages:
- stage: TerraformDeployment
  jobs:
  - job: DeployInfrastructure
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '3.x'
        installationPath: $(Agent.ToolsDirectory)/dotnet

    - script: |
        cd $(Build.Repository.LocalPath)/path/to/terraform/config
        terraform init
        terraform plan -out=tfplan -var="subscription_id=$(subscription_id)" -var="client_id=$(client_id)" -var="client_secret=$(client_secret)" -var="tenant_id=$(tenant_id)" -var="resource_group_name=$(resource_group_name)" -var="cluster_name=$(cluster_name)"
      displayName: 'Terraform Init and Plan'

    - script: |
        cd $(Build.Repository.LocalPath)/path/to/terraform/config
        terraform apply -auto-approve tfplan
      displayName: 'Terraform Apply'
